default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-beer_development

test:
  <<: *default
  database: rails-beer_test

# production:
#   <<: *default
#   database: db/production.sqlite3
